# KPI EDA

In [ ]:
import pandas as pd
import numpy as np
import openpyxl

In [72]:
def clean_date(df, date_col):
    df = df.copy()
    # # Auto convert date
    # df[date_col] = pd.to_datetime(df[date_col], errors="coerce")

    # ---- Fix your year-to-datetime issue ----
    # --- Safe datetime conversion for mixed cases ---
    if df[date_col].dtype == "int64":
        # only year → make it YYYY-01-01
        df[date_col] = pd.to_datetime(df[date_col].astype(str), format="%Y", errors="coerce")

    else:
        # covers: strings like "2020-01-01 00:00:00", "2020-01", etc.
        df[date_col] = pd.to_datetime(df[date_col], errors="coerce")

    # normalize all datetimes
    df[date_col] = df[date_col].dt.normalize()

    # # Auto convert numeric column
    # df[sum_col] = pd.to_numeric(df[sum_col], errors="coerce")
    return df

def group_and_sum(df, new_col_name, date_col, group_cols, granularity, sum_col):
    """
    Group a dataframe by a date granularity + other columns and sum a value column.

    Parameters:
    df (pd.DataFrame): Input dataframe.
    new_col_name (str): The name of the new summed column to create.
    date_col (str): Name of the date column.
    group_cols (list): Other columns to group by.
    granularity (str): 'day', 'month', or 'year'.
    sum_col (str): The column whose values will be summed.

    Returns:
    pd.DataFrame: Grouped + summed dataframe.
    """

    df = df.copy()

    # Ensure date column is datetime
    df[date_col] = pd.to_datetime(df[date_col])

    # Create grouped date column
    if granularity == "month":
        df["grouped_date"] = df[date_col].dt.to_period("M").dt.to_timestamp()
    elif granularity == "day":
        df["grouped_date"] = df[date_col].dt.date
    elif granularity == "year":
        df["grouped_date"] = df[date_col].dt.to_period("Y").dt.to_timestamp()
    else:
        raise ValueError("Granularity must be 'day', 'month', or 'year'.")

    # Group and sum
    grouped_df = (
        df.groupby(["grouped_date"] + group_cols)[sum_col]
          .sum()
          .reset_index()
          .rename(columns={sum_col: new_col_name})
    )

    return grouped_df


def simple_group_and_sum(df, group_cols, sum_cols):
    """
    Groups the dataframe by `group_cols` and sums only the columns in `sum_cols`.
    Drops all other columns except `group_cols`.
    
    Parameters:
        df (pd.DataFrame): Input dataframe
        group_cols (list): Columns to group by
        sum_cols (list): Columns to sum
    
    Returns:
        pd.DataFrame: Grouped and summed dataframe
    """
    df = df.copy()
    
    # Keep only group columns + columns to sum
    cols_to_keep = group_cols + sum_cols
    df = df[cols_to_keep]
    
    # Group and sum specified columns
    grouped_df = df.groupby(group_cols, as_index=False)[sum_cols].sum()
    
    return grouped_df

def kpi_rate_calc(df, kpi_name, col1, col2, flag=0):
    df = df.copy()
    tooltip = "Tool "+kpi_name
    kpi_name = kpi_name + " Rate"
    if flag==0:
        df[kpi_name] = ((df[col1] - df[col2]) * 100) / df[col1]
        df[tooltip] = (df[col1] - df[col2])
    elif flag==1:
        df[kpi_name] = (df[col1] * 100) / df[col2]
        df[tooltip] = df[col1]
    elif flag==2:
        df[kpi_name] = (df[col1]) / df[col2]
        df[tooltip] = df[col1]
    
    return df

def clean_country_city_zone_source(df):
    try:
        if 'country' in df.columns:
            df['country'] = df['country'].str.title()
        if 'city' in df.columns:
            df['city'] = df['city'].str.title()
        if 'zone' in df.columns:
            df['zone'] = df['zone'].str.title()
        if 'source' in df.columns:
            df['source'] = df['source'].str.title()
    except Exception as e:
        print(f"An error occurred: {e}")
        pass

def add_city_column_if_missing(df, city_zone_mapping_df):
    if 'city' not in df.columns and 'zone' in df.columns:
        merged_df = df.merge(city_zone_mapping_df[['zone', 'city']], on='zone', how='left')
        df['city'] = merged_df['city']
        df['city'] = df['city'].fillna('Unknown City')
        # print("City column added to df.")
    else:
        pass
        # print("City column already exists, skipping city-zone merge for df.")
    # display(df[:1])

In [73]:
all_fin_service_df = clean_date(pd.read_excel('Raw_Data/Master_Data.xlsx', sheet_name='all_fin_service'), 'date_MMYY')
all_national_df = clean_date(pd.read_excel('Raw_Data/Master_Data.xlsx', sheet_name='all_national'), 'date_YY')
billing_df = clean_date(pd.read_excel('Raw_Data/Master_Data.xlsx', sheet_name='agg_billing'), 'date_YYMM')
production_df = clean_date(pd.read_excel('Raw_Data/Master_Data.xlsx', sheet_name='production'), 'date_YYMMDD')
s_access_df = clean_date(pd.read_excel('Raw_Data/Master_Data.xlsx', sheet_name='s_access'), 'date_YY')
s_service_df = clean_date(pd.read_excel('Raw_Data/Master_Data.xlsx', sheet_name='s_service'), 'date_MMYY')
w_access_df = clean_date(pd.read_excel('Raw_Data/Master_Data.xlsx', sheet_name='w_access'), 'date_YY')
w_service_df = clean_date(pd.read_excel('Raw_Data/Master_Data.xlsx', sheet_name='w_service'), 'date_MMYY')
city_zone_mapping_df = pd.read_excel('Raw_Data/Master_Data.xlsx', sheet_name='city_zone_mapping')
master_list_df = [all_fin_service_df, all_national_df, billing_df,
                  production_df, s_access_df, s_service_df,
                  w_access_df, w_service_df, city_zone_mapping_df]

for df in master_list_df:
    clean_country_city_zone_source(df)
for df in master_list_df:
    add_city_column_if_missing(df, city_zone_mapping_df)
    # display(df[:1])

# city_zone_mapping_df = clean_country_city_zone_source(city_zone_mapping_df)

In [74]:
# agg_billing_df = simple_group_and_sum(
#     df=billing_df, group_cols=["source", "zone", "date_YYMM", "country"],
#     sum_cols=["billed", "paid", "consumption_m3"])

# total_billed_df = group_and_sum(
#     df=billing_df,new_col_name="nrw", date_col="date_YYMMDD",
#     group_cols=["zone"], granularity="month", sum_col="billed")

In [75]:
kpi1_billing_df = simple_group_and_sum(
    df=billing_df, group_cols=["zone", "date_YYMM", "country"],
    sum_cols=["billed", "paid", "consumption_m3"])
kpi1_billing_df.rename(columns={'billed': 'total_billed'}, inplace=True)
kpi1_billing_df.rename(columns={'paid': 'total_paid'}, inplace=True)
kpi1_billing_df = kpi_rate_calc(kpi1_billing_df, "NRW", "total_billed", "total_paid")
kpi1_billing_df.head()

,zone,date_YYMM,country,total_billed,total_paid,consumption_m3,NRW Rate,Tool NRW
0,Capital Hill,2020-01-01,Malawi,1.641193e+07,1.550517e+07,55440.970858,5.524954,906751.323840
1,Capital Hill,2020-02-01,Malawi,1.559113e+07,1.469274e+07,52443.569657,5.762165,898386.423115
2,Capital Hill,2020-03-01,Malawi,1.548439e+07,1.473864e+07,49768.797938,4.816140,745749.918189
3,Capital Hill,2020-04-01,Malawi,1.603569e+07,1.517490e+07,53574.873296,5.367959,860788.985445
4,Capital Hill,2020-05-01,Malawi,1.578724e+07,1.500149e+07,53135.912424,4.977109,785748.056151

In [ ]:
kpi2a4a5_all_fin_service_df = simple_group_and_sum(
    df=all_fin_service_df, group_cols=["city", "date_MMYY", "country"],
    sum_cols=["sewer_revenue", "opex", "complaints", "resolved", "blocks", "sewer_length"])

kpi2a4a5_all_fin_service_df.rename(columns={'sewer_revenue': 'total_sewer_revenue'}, inplace=True)
kpi2a4a5_all_fin_service_df.rename(columns={'opex': 'total_opex'}, inplace=True)
kpi2a4a5_all_fin_service_df = kpi_rate_calc(kpi2a4a5_all_fin_service_df, "SRC", "total_sewer_revenue", "total_opex", flag=1)

# kpi4a5_all_fin_service_df = simple_group_and_sum(
#     df=all_fin_service_df, group_cols=["city", "date_MMYY", "country"],
#     sum_cols=[])

kpi2a4a5_all_fin_service_df.rename(columns={'complaints': 'total_complaints'}, inplace=True)
kpi2a4a5_all_fin_service_df.rename(columns={'resolved': 'total_resolved'}, inplace=True)
kpi2a4a5_all_fin_service_df = kpi_rate_calc(kpi2a4a5_all_fin_service_df, "SUC", "total_complaints", "total_resolved", flag=0)

kpi2a4a5_all_fin_service_df.rename(columns={'blocks': 'total_blocks'}, inplace=True)
kpi2a4a5_all_fin_service_df.rename(columns={'sewer_length': 'total_sewer_length'}, inplace=True)
kpi2a4a5_all_fin_service_df = kpi_rate_calc(kpi2a4a5_all_fin_service_df, "SBK", "total_blocks", "total_sewer_length", flag=2)


kpi2a4a5_all_fin_service_df.head()

,city,date_MMYY,country,total_sewer_revenue,total_opex,total_complaints,total_resolved,total_blocks,total_sewer_length,SRC Rate,Tool SRC,SUC Rate,Tool SUC,SBK Rate,Tool SBK
0,Kampala,2020-01-01,Uganda,678007882,14498000000,588,492,256,106,4.676561,678007882,16.326531,96,2.415094,256
1,Kampala,2020-02-01,Uganda,360346932,18574000000,920,710,271,106,1.940061,360346932,22.826087,210,2.556604,271
2,Kampala,2020-03-01,Uganda,553023079,19298000000,672,536,203,106,2.865702,553023079,20.238095,136,1.915094,203
3,Kampala,2020-04-01,Uganda,590730660,14137000000,992,626,253,106,4.178614,590730660,36.895161,366,2.386792,253
4,Kampala,2020-05-01,Uganda,447566183,14761000000,786,601,205,106,3.032086,447566183,23.536896,185,1.933962,205

In [77]:

kpi3_all_fin_service_df = group_and_sum(
    df=all_fin_service_df,new_col_name="total_opex", date_col="date_MMYY",
    group_cols=["country", "city"], granularity="year", sum_col="opex")

kpi3_all_national_df = simple_group_and_sum(
    df=all_national_df, group_cols=["country", "city", "date_YY"],
    sum_cols=["budget_allocated"])
kpi3_all_national_df.rename(columns={'budget_allocated': 'total_budget_allocated'}, inplace=True)

kpi3_all_fin_service_df.rename(columns={'grouped_date': 'date_YY'}, inplace=True)

kpi3_df = pd.merge(kpi3_all_fin_service_df, kpi3_all_national_df,
                                 how="left",
                                 on=["country", "city", "date_YY"])

kpi3_df = kpi_rate_calc(kpi3_df, "OSB", "total_budget_allocated", "total_opex", flag=0)
kpi3_df.head()

,date_YY,country,city,total_opex,total_budget_allocated,OSB Rate,Tool OSB
0,2020-01-01,Cameroon,Yaounde,201037000000,258756000000,22.306343,57719000000
1,2020-01-01,Lesotho,Maseru,154939000000,231943000000,33.199536,77004000000
2,2020-01-01,Malawi,Lilongwe,156977000000,213276000000,26.397251,56299000000
3,2020-01-01,Uganda,Kampala,189898000000,334573000000,43.241684,144675000000
4,2021-01-01,Cameroon,Yaounde,212419000000,442520000000,51.997876,230101000000

In [78]:
kpi6a7_w_service_df = simple_group_and_sum(
    df=w_service_df, group_cols=["zone", "date_MMYY", "country"],
    sum_cols=["tests_passed_ecoli", "test_conducted_ecoli", "tests_ecoli",
              "test_passed_chlorine", "tests_conducted_chlorine", "tests_chlorine"])

kpi6a7_w_service_df.rename(columns={'tests_passed_ecoli': 'total_tests_passed_ecoli'}, inplace=True)
kpi6a7_w_service_df.rename(columns={'test_conducted_ecoli': 'total_test_conducted_ecoli'}, inplace=True)
kpi6a7_w_service_df.rename(columns={'tests_ecoli': 'total_tests_ecoli'}, inplace=True)

kpi6a7_w_service_df.rename(columns={'test_passed_chlorine': 'total_tests_passed_chlorine'}, inplace=True)
kpi6a7_w_service_df.rename(columns={'tests_conducted_chlorine': 'total_tests_conducted_chlorine'}, inplace=True)
kpi6a7_w_service_df.rename(columns={'tests_chlorine': 'total_tests_chlorine'}, inplace=True)

kpi6a7_w_service_df = kpi_rate_calc(kpi6a7_w_service_df, "ETF", "total_test_conducted_ecoli", "total_tests_passed_ecoli", flag=0)
kpi6a7_w_service_df = kpi_rate_calc(kpi6a7_w_service_df, "ETS", "total_tests_ecoli", "total_test_conducted_ecoli", flag=0)

kpi6a7_w_service_df = kpi_rate_calc(kpi6a7_w_service_df, "CTF", "total_tests_conducted_chlorine", "total_tests_passed_chlorine", flag=0)
kpi6a7_w_service_df = kpi_rate_calc(kpi6a7_w_service_df, "CTS", "total_tests_chlorine", "total_tests_conducted_chlorine", flag=0)

kpi6a7_w_service_df.head()

,zone,date_MMYY,country,total_tests_passed_ecoli,total_test_conducted_ecoli,total_tests_ecoli,total_tests_passed_chlorine,total_tests_conducted_chlorine,total_tests_chlorine,ETF Rate,Tool ETF,ETS Rate,Tool ETS,CTF Rate,Tool CTF,CTS Rate,Tool CTS
0,Capital Hill,2020-01-01,Malawi,80,88,100,126,140,150,9.090909,8,12.000000,12,10.000000,14,6.666667,10
1,Capital Hill,2020-02-01,Malawi,128,133,150,76,92,100,3.759398,5,11.333333,17,17.391304,16,8.000000,8
2,Capital Hill,2020-03-01,Malawi,135,163,200,183,185,200,17.177914,28,18.500000,37,1.081081,2,7.500000,15
3,Capital Hill,2020-04-01,Malawi,150,169,200,128,141,200,11.242604,19,15.500000,31,9.219858,13,29.500000,59
4,Capital Hill,2020-05-01,Malawi,152,160,200,69,78,100,5.000000,8,20.000000,40,11.538462,9,22.000000,22

In [85]:
kpi8_w_access_df = simple_group_and_sum(
    df=w_access_df, group_cols=["city", "date_YY", "country"],
    sum_cols=["popn_total", "households", "municipal_coverage"])
kpi8_w_access_df.rename(columns={'popn_total': 'total_popn_total'}, inplace=True)
kpi8_w_access_df.rename(columns={'households': 'total_households'}, inplace=True)
kpi8_w_access_df.rename(columns={'municipal_coverage': 'total_municipal_coverage'}, inplace=True)
kpi8_w_access_df["PPH"]=kpi8_w_access_df["total_popn_total"]/kpi8_w_access_df["total_households"]
kpi8_w_access_df["MHC"]=kpi8_w_access_df["total_municipal_coverage"]/kpi8_w_access_df["PPH"]

# If date_MMYY is a string, ensure it's converted to datetime
kpi8_all_fin_service_df = all_fin_service_df.copy()
kpi8_all_fin_service_df['date_MMYY'] = pd.to_datetime(kpi8_all_fin_service_df['date_MMYY'])
# Extract year
kpi8_all_fin_service_df['year'] = kpi8_all_fin_service_df['date_MMYY'].dt.year
# If date_YY is a string or datetime, convert and extract year
kpi8_w_access_df['date_YY'] = pd.to_datetime(kpi8_w_access_df['date_YY'], format='%Y')
kpi8_w_access_df['year'] = kpi8_w_access_df['date_YY'].dt.year
kpi8_df = kpi8_all_fin_service_df.merge(
    kpi8_w_access_df[['year', 'MHC', 'city', 'country']],
    on=['year', 'city', 'country'],
    how='left'
)
# kpi8_df['WSH'] = kpi8_df['w_staff'] / kpi8_df['MHC']
kpi8_df = kpi_rate_calc(kpi8_df, "WSH", "w_staff", "MHC", flag=1)

kpi8_df.head()

,country,city,date_MMYY,sewer_length,complaints,resolved,blocks,sewer_billed,sewer_revenue,opex,san_staff,w_staff,propoor_popn,year,MHC,WSH Rate,Tool WSH
0,Cameroon,Yaounde,2020-01-01,159,756,634,115,670000000,540849679,12741000000,306,538,141899,2020,219764.612532,0.244807,538
1,Cameroon,Yaounde,2020-02-01,159,466,399,108,680000000,557247509,18790000000,347,473,134412,2020,219764.612532,0.215230,473
2,Cameroon,Yaounde,2020-03-01,159,622,528,100,617000000,519471394,16889000000,305,484,218679,2020,219764.612532,0.220236,484
3,Cameroon,Yaounde,2020-04-01,159,734,671,112,604000000,507728739,21220000000,366,535,89807,2020,219764.612532,0.243442,535
4,Cameroon,Yaounde,2020-05-01,159,323,322,91,594000000,514747374,16617000000,525,364,77991,2020,219764.612532,0.165632,364

In [88]:
kpi9_s_service_df = simple_group_and_sum(
    df=s_service_df, group_cols=["city", "date_MMYY", "country"],
    sum_cols=["sewer_connections"])
kpi9_s_service_df.rename(columns={'sewer_connections': 'total_sewer_connections'}, inplace=True)
kpi9_all_fin_service_df = all_fin_service_df.copy()

kpi9_df = kpi9_all_fin_service_df.merge(
    kpi9_s_service_df[["city", "date_MMYY", "country", 'total_sewer_connections']],
    on=['date_MMYY', 'city', 'country'],
    how='left'
)

# kpi9_df['Sewer_Connections'] = kpi9_df['sewer_connections'] / kpi9_df['total_sewer_connections']
kpi9_df = kpi_rate_calc(kpi9_df, "SSC", "san_staff", "total_sewer_connections", flag=1)

kpi9_df.head()

,country,city,date_MMYY,sewer_length,complaints,resolved,blocks,sewer_billed,sewer_revenue,opex,san_staff,w_staff,propoor_popn,total_sewer_connections,SSC Rate,Tool SSC
0,Cameroon,Yaounde,2020-01-01,159,756,634,115,670000000,540849679,12741000000,306,538,141899,39869,0.767514,306
1,Cameroon,Yaounde,2020-02-01,159,466,399,108,680000000,557247509,18790000000,347,473,134412,39869,0.870350,347
2,Cameroon,Yaounde,2020-03-01,159,622,528,100,617000000,519471394,16889000000,305,484,218679,39869,0.765005,305
3,Cameroon,Yaounde,2020-04-01,159,734,671,112,604000000,507728739,21220000000,366,535,89807,39869,0.918006,366
4,Cameroon,Yaounde,2020-05-01,159,323,322,91,594000000,514747374,16617000000,525,364,77991,39869,1.316813,525

In [105]:
kpi10_production_df = group_and_sum(
    df=production_df,new_col_name="total_production", date_col="date_YYMMDD",
    group_cols=["country"], granularity="month", sum_col="production_m3")
kpi10_production_df.rename(columns={'grouped_date': 'date_MMYY'}, inplace=True)

kpi10_w_service_df = simple_group_and_sum(
    df=w_service_df, group_cols=["date_MMYY", "country"],
    sum_cols=["total_consumption"])
kpi10_w_service_df.rename(columns={'total_consumption': 'grand_total_consumption'}, inplace=True)

kpi10_df = kpi10_w_service_df.merge(
    kpi10_production_df[["date_MMYY", "country", 'total_production']],
    on=['date_MMYY', 'country'],
    how='left'
)

kpi10_df = kpi_rate_calc(kpi10_df, "NCW", "total_production", "grand_total_consumption", flag=0)
kpi10_df.head()

,date_MMYY,country,grand_total_consumption,total_production,NCW Rate,Tool NCW
0,2020-01-01,Cameroon,6744862,716897,-840.841153,-6027965
1,2020-01-01,Lesotho,2049164,731330,-180.196902,-1317834
2,2020-01-01,Malawi,2601813,697299,-273.127310,-1904514
3,2020-01-01,Uganda,2746996,698301,-293.382796,-2048695
4,2020-02-01,Cameroon,4977448,640340,-677.313302,-4337108

In [107]:
kpi11_w_service_df = simple_group_and_sum(
    df=w_service_df, group_cols=["date_MMYY", "zone", "country"],
    sum_cols=["total_consumption", "metered"])
kpi11_w_service_df.rename(columns={'total_consumption': 'grand_total_consumption'}, inplace=True)
kpi11_w_service_df.rename(columns={'metered': 'total_metered'}, inplace=True)
kpi11_w_service_df = kpi_rate_calc(kpi11_w_service_df, "NMW", "grand_total_consumption", "total_metered", flag=0)
kpi11_w_service_df.head()

,date_MMYY,zone,country,grand_total_consumption,total_metered,NMW Rate,Tool NMW
0,2020-01-01,Capital Hill,Malawi,1011107,29931,97.039779,981176
1,2020-01-01,Central,Uganda,971544,95951,90.123865,875593
2,2020-01-01,Kanengo,Malawi,564993,3014,99.466542,561979
3,2020-01-01,Kawempe,Uganda,292558,225104,23.056625,67454
4,2020-01-01,Lumbadzi,Malawi,354812,853,99.759591,353959

In [113]:
kpi12_w_service_df = simple_group_and_sum(
    df=w_access_df, group_cols=["date_YY", "zone", "country"],
    sum_cols=["popn_total", "municipal_coverage"])
kpi12_w_service_df.rename(columns={'popn_total': 'grand_popn_total'}, inplace=True)
kpi12_w_service_df.rename(columns={'municipal_coverage': 'total_municipal_coverage'}, inplace=True)
kpi12_w_service_df = kpi_rate_calc(kpi12_w_service_df, "PUW", "grand_popn_total", "total_municipal_coverage", flag=0)
kpi12_w_service_df.head()

,date_YY,zone,country,grand_popn_total,total_municipal_coverage,PUW Rate,Tool PUW
0,2020-01-01,Capital Hill,Malawi,446463,37741,91.546668,408722
1,2020-01-01,Central,Uganda,450476,118494,73.695824,331982
2,2020-01-01,Kanengo,Malawi,38290,3420,91.068164,34870
3,2020-01-01,Kawempe,Uganda,831427,305166,63.296116,526261
4,2020-01-01,Lumbadzi,Malawi,14953,1167,92.195546,13786

In [114]:
kpi13_s_service_df = simple_group_and_sum(
    df=s_service_df, group_cols=["date_MMYY", "zone", "country"],
    sum_cols=["households", "sewer_connections"])
kpi13_s_service_df.rename(columns={'households': 'total_households'}, inplace=True)
kpi13_s_service_df.rename(columns={'sewer_connections': 'total_sewer_connections'}, inplace=True)
kpi13_s_service_df = kpi_rate_calc(kpi13_s_service_df, "HUS", "total_households", "total_sewer_connections", flag=0)
kpi13_s_service_df.head()

,date_MMYY,zone,country,total_households,total_sewer_connections,HUS Rate,Tool HUS
0,2020-01-01,Capital Hill,Malawi,103168,5786,94.391672,97382
1,2020-01-01,Central,Uganda,103106,4383,95.749035,98723
2,2020-01-01,Kanengo,Malawi,8795,310,96.475270,8485
3,2020-01-01,Kawempe,Uganda,190135,11486,93.959029,178649
4,2020-01-01,Lumbadzi,Malawi,3474,92,97.351756,3382

# EDA

In [ ]:
import pandas as pd
import numpy as np
import openpyxl

all_fin_service_df = pd.read_excel('Raw_Data/Master_Data.xlsx', sheet_name='all_fin_service')
all_national_df = pd.read_excel('Raw_Data\Master_Data.xlsx', sheet_name='all_national')
billing_df = pd.read_excel('Raw_Data\Master_Data.xlsx', sheet_name='agg_billing')
production_df = pd.read_excel('Raw_Data\Master_Data.xlsx', sheet_name='production')
s_access_df = pd.read_excel('Raw_Data\Master_Data.xlsx', sheet_name='s_access')
s_service_df = pd.read_excel('Raw_Data\Master_Data.xlsx', sheet_name='s_service')
w_access_df = pd.read_excel('Raw_Data\Master_Data.xlsx', sheet_name='w_access')
w_service_df = pd.read_excel('Raw_Data\Master_Data.xlsx', sheet_name='w_service')
# Further processing can be done on the dataframes as needed

In [ ]:
display(all_fin_service_df.head())
display(all_national_df.head())
display(billing_df.head())
display(production_df.head())
display(s_access_df.head())
display(s_service_df.head())
display(w_access_df.head())
display(w_service_df.head())

In [ ]:

def simple_group_and_sum(df, group_cols, sum_cols):
    """
    Groups the dataframe by `group_cols` and sums only the columns in `sum_cols`.
    Drops all other columns except `group_cols`.
    
    Parameters:
        df (pd.DataFrame): Input dataframe
        group_cols (list): Columns to group by
        sum_cols (list): Columns to sum
    
    Returns:
        pd.DataFrame: Grouped and summed dataframe
    """
    df = df.copy()
    
    # Keep only group columns + columns to sum
    cols_to_keep = group_cols + sum_cols
    df = df[cols_to_keep]
    
    # Group and sum specified columns
    grouped_df = df.groupby(group_cols, as_index=False)[sum_cols].sum()
    
    return grouped_df

In [ ]:
print(type(billing_df["date_YYMM"].iloc[0]))
print(type(all_fin_service_df["date_MMYY"].iloc[0]))

In [ ]:
# billing_df['date_YYMM'] = pd.to_datetime(billing_df['date_YYMMDD']).dt.to_period('M')
# agg_billing_df = group_and_sum(
#     df=billing_df, group_cols=["source", "zone", "date_YYMM", "country"], sum_cols=["billed", "paid", "consumption_m3"])
# billing_df.shape
# # agg_billing_df.head()
# # agg_billing_df.shape
# # agg_billing_df.to_csv('agg_master_billing.csv', index=False)

# # agg_billing_df["date_YYMM"].unique()
# # type(agg_billing_df["date_YYMM"].iloc[0])

# # agg_billing_df.tail()
# # billing_df.head()
# # billing_df.tail()
# agg_billing_df[agg_billing_df[agg_billing_df["date_YYMM"] == "2024-01"]]["country"] == "uganda"

In [ ]:
# import pandas as pd

# def fix_uganda_dates_vectorized(df, date_col='date_YYMMDD', country_col='country'):
#     df = df.copy()
    
#     # Mask for Uganda rows
#     mask = df[country_col].str.lower() == 'uganda'
    
#     # Convert the column to datetime first (coerce errors to NaT)
#     df[date_col] = pd.to_datetime(df[date_col], errors='coerce', infer_datetime_format=True)
    
#     # Extract year, month, day for Uganda rows
#     uganda_dates = df.loc[mask, date_col]
#     year = uganda_dates.dt.year
#     month = uganda_dates.dt.month
#     day = uganda_dates.dt.day
    
#     # Swap month and day
#     df.loc[mask, date_col] = pd.to_datetime(
#         dict(year=year, month=day, day=month),
#         errors='coerce'
#     )
    
#     return df


# billing_df = fix_uganda_dates_vectorized(billing_df, date_col='date_YYMMDD', country_col='country')
# billing_df.rename(columns={'date_YYMMDD': 'date_YYMM'}, inplace=True)

In [ ]:
# billing_df.to_csv('master_billing.csv', index=False)

# # # Convert to datetime
# # billing_df['date_YYMM'] = billing_df['date_YYMM'].dt.to_timestamp()

# # print(billing_df["date_YYMMDD"].iloc[-1])
# # print(type(billing_df["date_YYMMDD"].iloc[0]))
# # print(billing_df["date_YYMM"].iloc[-1])
# # print(type(billing_df["date_YYMM"].iloc[0]))

In [ ]:
uganda = billing_df[billing_df['country']=='uganda']
# uganda.head()
# uganda.tail()
# uganda.shape
# agg_uganda = group_and_sum(
#     df=uganda, group_cols=["source", "zone", "date_YYMM", "country"], sum_cols=["billed", "paid", "consumption_m3"])

# agg_uganda.tail()
# agg_uganda['date_YYMM'] = pd.to_datetime(agg_uganda['date_YYMM']).dt.to_period('M')

# type(agg_uganda["date_YYMM"].iloc[0])

# Old

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
w_service_malawi = pd.read_csv("Raw_Data\malawi\w_service_malawi.csv")
df = w_service_malawi.copy()
df["date"] = pd.to_datetime(
    df["date"], format="%b-%y", errors="coerce"
)

# df["date"] = df["date"].dt.strftime("%b-%y")

In [ ]:
display(df.head())
# Group by date and sum across all zones
df_sum = df.groupby("date", as_index=False)[["total_consumption", "metered"]].sum().sort_values("date")
display(df_sum.head())

In [ ]:
from matplotlib.dates import DateFormatter

# Read your data; CSV should have columns: date,total_consumption,metered
# Example CSV header: date,total_consumption,metered
# df = w_service_malawi

plt.figure(figsize=(10,5))
plt.plot(df_sum['date'], df_sum['total_consumption'], marker='o', label='Total consumption')
plt.plot(df_sum['date'], df_sum['metered'], marker='o', label='Metered')
plt.xlabel('Date')
plt.ylabel('Value')
plt.title('Total consumption vs Metered')
plt.legend()
plt.grid(True)
# plt.gca().xaxis.set_major_formatter(DateFormatter('%Y-%m'))
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
fig, ax1 = plt.subplots(figsize=(10,5))

# Primary axis for total_consumption
ax1.plot(df_sum['date'], df_sum['total_consumption'], marker='o', color='tab:blue', label='Total consumption')
ax1.set_xlabel('Date')
ax1.set_ylabel('Total consumption', color='tab:blue')
ax1.tick_params(axis='y', labelcolor='tab:blue')

# Secondary axis for metered
ax2 = ax1.twinx()
ax2.plot(df_sum['date'], df_sum['metered'], marker='o', color='tab:orange', label='Metered')
ax2.set_ylabel('Metered', color='tab:orange')
ax2.tick_params(axis='y', labelcolor='tab:orange')

# Common elements
plt.title('Total consumption vs Metered')
ax1.grid(True)
fig.tight_layout()
plt.xticks(rotation=45)

plt.show()